languages:
  PHP: true
exclude_paths:
- "TestSuite/*"
- "Documentation/*"
- "Component/Captcha/Vendor/SimplePhpCaptcha/*"
- "Component/Database/Vendor/Doctrine2Annotations/*"
- "Component/Database/Vendor/Doctrine2Cache/*"
- "Component/Database/Vendor/Doctrine2Collections/*"
- "Component/Database/Vendor/Doctrine2Common/*"
- "Component/Database/Vendor/Doctrine2DBAL/*"
- "Component/Database/Vendor/Doctrine2Instantiator/*"
- "Component/Database/Vendor/Doctrine2Lexer/*"
- "Component/Database/Vendor/Doctrine2ORM/*"
- "Component/Document/Vendor/PhpExcel/*"
- "Component/Document/Vendor/PhpWord/*"
- "Component/Document/Vendor/DomPdf/*"
- "Component/Document/Vendor/mPdf/*"
- "Component/Documentation/Vendor/ApiGen/*"
- "Component/Documentation/Vendor/Template/*"
- "Component/Mail/Vendor/EdenPhpMail/*"
- "Component/Packer/Vendor/PclZip/*"
- "Component/Router/Vendor/Symfony/*"
- "Component/Template/Vendor/Twig/*"
- "Component/Template/Vendor/TwigExtension/*"
- "Component/Template/Vendor/Smarty/*"
- "Core/HttpKernel/Vendor/Symfony/*"
- "Core/FileSystem/Vendor/Symfony/*"
- "Core/SecureKernel/Vendor/PhpSecLib/*"
