<?php

namespace SPHERE\Application\Api\Document\Standard\Repository;

use SPHERE\Application\Api\Document\AbstractDocument;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportBFS\F01;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportFS\B01;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportFS\B02;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportFS\K01;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportFS\N01;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportFS\N03;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportFS\N05;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportFS\S01;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportFS\S02;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportFS\S04;
use SPHERE\Application\Api\Document\Standard\Repository\KamenzReportFS\S04_1_1;
use SPHERE\Application\Document\Generator\Repository\Document;
use SPHERE\Application\Document\Generator\Repository\Frame;
use SPHERE\Application\Document\Generator\Repository\Page;

/**
 * Class KamenzReportFS
 *
 * @package SPHERE\Application\Api\Document\Standard\Repository
 */
class KamenzReportFS extends AbstractDocument
{
    /**
     * @return string
     */
    public function getName()
    {
        return 'Kamenz-Statistik';
    }

    /**
     *
     * @param array $pageList
     * @param string $Part
     *
     * @return Frame
     */
    public function buildDocument(array $pageList = array(), string $Part = '0'): Frame
    {
        $document = (new Document());
        if ($Part == '1') {
            $document
                ->addPage((new Page())
                    ->addSliceArray(B01::getContent('B01_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B01::getContent('B01_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B01::getContent('B01_1_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B01::getContent('B01_1_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B01::getContent('B01_2_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B01::getContent('B01_2_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B01::getContent('B01_2_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B01::getContent('B01_2_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B02::getContent('B02_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B02::getContent('B02_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B02::getContent('B02_1_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B02::getContent('B02_1_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B02::getContent('B02_2_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B02::getContent('B02_2_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B02::getContent('B02_2_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(B02::getContent('B02_2_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(F01::getContent('F01_1', 'Fachschule'))
                )
                ->addPage((new Page())
                    ->addSliceArray(F01::getContent('F01_2', 'Fachschule'))
                )
                ->addPage((new Page())
                    ->addSliceArray(K01::getContent())
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N01_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N01_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N01_1_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N01_1_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N01_2_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N01_2_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N01_2_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N01_2_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N02_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N02_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N02_1_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N02_1_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N02_2_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N02_2_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N02_2_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N01::getContent('N02_2_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N03_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N03_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N03_1_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N03_1_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N03_2_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N03_2_U'))
                );
        } elseif ($Part == '2') {
            $document
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N03_2_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N03_2_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N04_1_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N04_1_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N04_2_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N03::getContent('N04_2_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N05::getContent('N05_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N05::getContent('N05_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N05::getContent('N05_1_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N05::getContent('N05_1_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N05::getContent('N05_2_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N05::getContent('N05_2_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N05::getContent('N05_2_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(N05::getContent('N05_2_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S01::getContent('S01_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S01::getContent('S01_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S01::getContent('S01_1_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S01::getContent('S01_1_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S01::getContent('S01_2_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S01::getContent('S01_2_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S01::getContent('S01_2_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S01::getContent('S01_2_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S02_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S02_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S02_1_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S02_1_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S02_2_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S02_2_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S02_2_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S02_2_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S03_1_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S03_1_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S03_2_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S02::getContent('S03_2_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S04::getContent('S04_1_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S04::getContent('S04_1_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S04_1_1::getContent('S04_1_1'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S04::getContent('S04_2_A'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S04::getContent('S04_2_U'))
                )
                ->addPage((new Page())
                    ->addSliceArray(S04_1_1::getContent('S04_2_1'))
                );
        }

        return (new Frame())->addDocument($document);
    }
}