<?php
namespace SPHERE\Application\Api\Document\Standard\Repository;

use SPHERE\Application\Api\Document\AbstractDocument;
use SPHERE\Application\Document\Generator\Repository\Document;
use SPHERE\Application\Document\Generator\Repository\Element;
use SPHERE\Application\Document\Generator\Repository\Frame;
use SPHERE\Application\Document\Generator\Repository\Page;
use SPHERE\Application\Document\Generator\Repository\Section;
use SPHERE\Application\Document\Generator\Repository\Slice;

/**
 * Class StudentCard
 *
 * @package SPHERE\Application\Api\Document\Standard\Repository
 */
class StudentCard extends AbstractDocument
{

    /**
     * @return string
     */
    public function getName()
    {

        return 'Schülerkartei';
    }

    /**
     * @return Frame
     */
    public function buildDocument()
    {

        $SmallTextSize = '7px';
        $InputText = '12px';
        $OutLines = '1.2px';
        $HeightThreeLineBlock = '75px';
        $HeightTwoLineBlock = '20px';

        $SpaceBetween = '60px';

        $HeightForHeader = '100px';
        $InputFieldTop = '4px';
        $InputFieldTextSize = '13px';
        $InputFieldHeight = '20px';

        return ( new Frame() )->addDocument(( new Document() )
            ->addPage(( new Page() )
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addElementColumn(( new Element() )
                            ->setContent('A')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('B')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('C')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('D')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('E')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('F')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('G')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('H')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('I')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('J')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('K')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('L')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('N')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('M')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('O')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('P')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('Q')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('R')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('S')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('T')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('U')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('V')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('W')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('XY')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('Z')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                            ->styleAlignCenter()
                            , '4%')
                    )
                )
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addElementColumn(( new Element() )
                            ->setContent('Schülerkartei')
                            ->stylePaddingTop('10px')
                            ->stylePaddingBottom('5px')
                            ->styleTextSize('18px')
                            ->styleTextBold()
                        )
                    )
                )
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addSliceColumn(( new Slice() )
                            ->addSectionList(array(
                                ( new Section() )
                                    ->addElementColumn(( new Element() )
                                        ->setContent('Familienname/Vorname')
                                        ->stylePaddingLeft()
                                        ->styleTextSize($SmallTextSize)
                                        ->styleBorderTop($OutLines)
                                        ->styleBorderLeft($OutLines)
                                    ),
                                ( new Section() )
                                    ->addElementColumn(( new Element() )
                                        ->setContent('
                                            {% if( Content.Person.Data.Name.First is not empty) %}
                                                {{ Content.Person.Data.Name.Last }} {{ Content.Person.Data.Name.First }}
                                            {% else %}
                                                &nbsp;
                                            {% endif %}')
                                        ->stylePaddingLeft()
                                        ->styleTextSize($InputText)
                                        ->styleBorderBottom('0.5px')
                                        ->styleBorderLeft($OutLines)
                                        ->styleHeight('19px')
                                    ),
                                ( new Section() )
                                    ->addElementColumn(( new Element() )
                                        ->setContent('Anschrift')
                                        ->stylePaddingLeft()
                                        ->styleTextSize($SmallTextSize)
                                        ->styleBorderLeft($OutLines)
                                    ),
                                ( new Section() )
                                    ->addElementColumn(( new Element() )
                                        ->setContent('
                                            {% if(Content.Person.Address.Street.Name) %}
                                                {{ Content.Person.Address.Street.Name }}
                                                {{ Content.Person.Address.Street.Number }}
                                                {{ Content.Person.Address.City.Code }}
                                                {{ Content.Person.Address.City.Name }}
                                            {% else %}
                                                  &nbsp;
                                            {% endif %}')
                                        ->stylePaddingLeft()
                                        ->styleTextSize($InputText)
                                        ->styleBorderBottom('0.5px')
                                        ->styleBorderLeft($OutLines)
                                        ->styleHeight('19px')
                                    ),
                                ( new Section() )
                                    ->addElementColumn(( new Element() )
                                        ->setContent('Geschlecht')
                                        ->stylePaddingLeft()
                                        ->styleTextSize($SmallTextSize)
                                        ->styleBorderLeft($OutLines)
                                        , '21%')
                                    ->addElementColumn(( new Element() )
                                        ->setContent('Geburtsdatum')
                                        ->stylePaddingLeft()
                                        ->styleTextSize($SmallTextSize)
                                        ->styleBorderLeft('0.5px')
                                        , '21%')
                                    ->addElementColumn(( new Element() )
                                        ->setContent('Geburtsort')
                                        ->stylePaddingLeft()
                                        ->styleTextSize($SmallTextSize)
                                        ->styleBorderLeft('0.5px')
                                        , '74%'),
                                ( new Section() )
                                    ->addElementColumn(( new Element() )
                                        ->setContent('
                                            {% if Content.Person.Common.BirthDates.Gender == 1 %}
                                                männlich
                                            {% else %}
                                                {% if Content.Person.Common.BirthDates.Gender == 2 %}
                                                    weiblich
                                                {% else %}
                                                    &nbsp;
                                                {% endif %}
                                            {% endif %}
                                        ')
                                        ->stylePaddingLeft()
                                        ->styleTextSize($InputText)
                                        ->styleBorderLeft($OutLines)
                                        ->styleHeight('19px')
                                        , '21%')
                                    ->addElementColumn(( new Element() )
                                        ->setContent('
                                        {% if(Content.Person.Common.BirthDates.Birthday is not empty) %}
                                            {{ Content.Person.Common.BirthDates.Birthday|date("d.m.Y") }}
                                        {% else %}
                                            &nbsp;
                                        {% endif %}
                                        ')
                                        ->stylePaddingLeft()
                                        ->styleTextSize($InputText)
                                        ->styleBorderLeft('0.5px')
                                        ->styleHeight('19px')
                                        , '21%')
                                    ->addElementColumn(( new Element() )
                                        ->setContent('
                                        {% if(Content.Person.Common.BirthDates.Birthplace is not empty) %}
                                            {{ Content.Person.Common.BirthDates.Birthplace }}
                                        {% else %}
                                            &nbsp;
                                        {% endif %}
                                        ')
                                        ->stylePaddingLeft()
                                        ->styleTextSize($InputText)
                                        ->styleBorderLeft('0.5px')
                                        ->styleHeight('19px')
                                        , '74%')
                            ))
                            , '70%')
                        ->addSliceColumn(( new Slice() )
                            ->addSection(( new Section() )
                                ->addElementColumn(( new Element() )
                                    ->setContent('Schule')
                                    ->stylePaddingLeft()
                                    ->styleTextSize($SmallTextSize)
                                    ->styleBorderTop($OutLines)
                                    ->styleBorderRight($OutLines)
                                    ->styleBorderLeft('0.5px')
                                )
                            )
                            ->addSection(( new Section() )
                                ->addElementColumn(( new Element() )
                                    ->setContent('
                                    {% if(Content.Student.Company is not empty) %}
                                            {{ Content.Student.Company }} 
                                            {% if(Content.Student.Company2 is not empty) %}
                                                <br/> {{ Content.Student.Company2 }}
                                            {% else %}
                                                &nbsp;
                                            {% endif %}
                                        {% else %}
                                            &nbsp;
                                        {% endif %}
                                    ')
                                    ->stylePaddingLeft()
                                    ->styleTextSize($InputText)
                                    ->styleBorderRight($OutLines)
                                    ->styleBorderLeft('0.5px')
                                    ->styleHeight($HeightThreeLineBlock)
                                )
                            )
                            , '30%')
                    )
                )
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addSliceColumn(( new Slice() )
                            ->addSection(( new Section() )
                                ->addElementColumn(( new Element() )
                                    ->setContent('Religionszugehörigkeit')
                                    ->stylePaddingLeft()
                                    ->styleTextSize($SmallTextSize)
                                    ->styleBorderTop('0.5px')
                                    ->styleBorderLeft($OutLines)
                                    , '21%')
                                ->addElementColumn(( new Element() )
                                    ->setContent('Staatsangehörigkeit*')
                                    ->stylePaddingLeft()
                                    ->styleTextSize($SmallTextSize)
                                    ->styleBorderTop('0.5px')
                                    ->styleBorderLeft('0.5px')
                                    , '21%')
                                ->addElementColumn(( new Element() )
                                    ->setContent('Telefon')
                                    ->stylePaddingLeft()
                                    ->styleTextSize($SmallTextSize)
                                    ->styleBorderTop('0.5px')
                                    ->styleBorderLeft('0.5px')
                                    , '74%')
                            )
                            , '70%')
                        ->addSliceColumn(( new Slice() )
                            ->addElement(( new Element() )
                                ->setContent('Notfallnummer')
                                ->stylePaddingLeft()
                                ->styleTextSize($SmallTextSize)
                                ->styleBorderTop('0.5px')
                                ->styleBorderLeft('0.5px')
                                ->styleBorderRight($OutLines)
                            )
                            , '30%')
                    )
                )
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addSliceColumn(( new Slice() )
                            ->addSection(( new Section() )
                                ->addElementColumn(( new Element() )
                                    ->setContent('
                                        {% if(Content.Person.Common.Denomination is not empty) %}
                                                {{ Content.Person.Common.Denomination }}
                                            {% else %}
                                                &nbsp;
                                            {% endif %}
                                        ')
                                    ->stylePaddingLeft()
                                    ->styleTextSize($InputText)
                                    ->styleBorderLeft($OutLines)
                                    ->styleHeight('19px')
                                    , '21%')
                                ->addElementColumn(( new Element() )
                                    ->setContent('
                                        {% if(Content.Person.Common.Nationality is not empty) %}
                                            {{ Content.Person.Common.Nationality }}
                                        {% else %}
                                            &nbsp;
                                        {% endif %}
                                        ')
                                    ->stylePaddingLeft()
                                    ->styleTextSize($InputText)
                                    ->styleBorderLeft('0.5px')
                                    ->styleHeight('19px')
                                    , '21%')
                                ->addElementColumn(( new Element() )
                                    ->setContent('
                                        {% if(Content.Person.Contact.Phone.Number is not empty) %}
                                            {{ Content.Person.Contact.Phone.Number }}
                                        {% else %}
                                            &nbsp;
                                        {% endif %}
                                        ')
                                    ->stylePaddingLeft()
                                    ->styleTextSize($InputText)
                                    ->styleBorderLeft('0.5px')
                                    ->styleHeight('19px')
                                    , '74%')
                            )
                            , '70%')
                        ->addSliceColumn(( new Slice() )
                            ->addElement(( new Element() )
                                ->setContent('
                                    {% if(Content.Person.Contact.Phone.Emergency1 is not empty) %}
                                        {{ Content.Person.Contact.Phone.Emergency1 }}
                                    {% else %}
                                        &nbsp;
                                    {% endif %}
                                    ')
                                ->stylePaddingLeft()
                                ->styleTextSize($InputText)
                                ->styleBorderRight($OutLines)
                                ->styleBorderLeft('0.5px')
                                ->styleHeight('19px')
                            )
                            , '30%')
                    )
                )
                ->addSlice(( new Slice() )
                    ->addElement(( new Element() )
                        ->setContent('Familienname/Vorname der Eltern')
                        ->stylePaddingLeft()
                        ->styleTextSize($SmallTextSize)
                        ->styleBorderTop('0.5px')
                        ->styleBorderLeft($OutLines)
                        ->styleBorderRight($OutLines)
                    )
                    ->addElement(( new Element() )
                        ->setContent('
                        {% if(Content.Person.Parent.Mother.Name.Last is not empty) %}
                            {% if(Content.Person.Parent.Father.Name.Last is not empty) %}
                                {{ Content.Person.Parent.Mother.Name.Last }} {{ Content.Person.Parent.Mother.Name.First }},
                                {{ Content.Person.Parent.Father.Name.Last }} {{ Content.Person.Parent.Father.Name.First }}
                            {% else %}
                                {{ Content.Person.Parent.Mother.Name.Last }} {{ Content.Person.Parent.Mother.Name.First }}
                            {% endif %}
                        {% else %}
                            {% if(Content.Person.Parent.Father.Name.Last is not empty) %}
                                {{ Content.Person.Parent.Father.Name.Last }} {{ Content.Person.Parent.Father.Name.First }}
                                {% else %}
                                &nbsp;
                            {% endif %}
                        {% endif %}
                        ')
                        ->stylePaddingLeft()
                        ->styleTextSize($InputText)
                        ->styleBorderLeft($OutLines)
                        ->styleBorderRight($OutLines)
                        ->styleHeight('19px')
                    )
                )
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addSliceColumn(( new Slice() )
                            ->addElement(( new Element() )
                                ->setContent('Beginn der Schulpflicht: Zurückstellung / vorzeitige Einschulung / Aufnahme¹')//ToDO auslesen aus der Schülerakte (später)
                                ->styleTextSize('13.5px')
                                ->stylePaddingTop($HeightTwoLineBlock)
                                ->stylePaddingLeft()
                                ->styleBorderTop('0.5px')
                                ->styleBorderRight('0.5px')
                                ->styleBorderLeft($OutLines)
                                ->styleHeight('36px')
                            )
                            , '70%')
                        ->addSliceColumn(( new Slice() )
                            ->addElement(( new Element() )
                                ->setContent('Einschulung am')
                                ->stylePaddingLeft()
                                ->styleTextSize($SmallTextSize)
                                ->styleBorderTop('0.5px')
                                ->styleBorderRight($OutLines)
                            )
                            ->addElement(( new Element() )
                                ->setContent('
                                {% if(Content.Student.School.Attendance.Date is not empty) %}
                                    {{ Content.Student.School.Attendance.Date }}
                                {% else %}
                                    &nbsp;
                                {% endif %}
                                ')
                                ->stylePaddingLeft()
                                ->styleTextSize($InputText)
                                ->styleHeight('19.5px')
                                ->styleBorderRight($OutLines)
                            )
                            ->addElement(( new Element() )
                                ->setContent('Schuljahr')
                                ->stylePaddingLeft()
                                ->styleTextSize($SmallTextSize)
                                ->styleBorderTop('0.5px')
                                ->styleBorderRight($OutLines)
                            )
                            ->addElement(( new Element() )
                                ->setContent('
                                {% if(Content.Student.School.Attendance.Year is not empty) %}
                                    {{ Content.Student.School.Attendance.Year }}
                                {% else %}
                                    &nbsp;
                                {% endif %}
                                ')
                                ->stylePaddingLeft()
                                ->styleTextSize($InputText)
                                ->styleHeight('19px')
                                ->styleBorderRight($OutLines)
                            )
                            , '30%')
                    )
                )
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addElementColumn(( new Element() )
                            ->setContent('Bildungsempfehlung für Mittelschule / Gymnasium¹: Aufnahmeürüfung Ja/Nein¹')//ToDO auslesen aus der Schülerakte (später)
                            ->styleTextSize('13.5px')
                            ->stylePaddingTop('6px')
                            ->stylePaddingLeft()
                            ->styleBorderTop('0.5px')
                            ->styleBorderRight('0.5px')
                            ->styleBorderLeft($OutLines)
                            ->styleHeight('22px')
                            , '70%')
                        ->addSliceColumn(( new Slice() )
                            ->addElement(( new Element() )
                                ->setContent('Schuljahr')
                                ->stylePaddingLeft()
                                ->styleTextSize($SmallTextSize)
                                ->styleBorderTop('0.5px')
                                ->styleBorderRight($OutLines)
                            )
                            ->addElement(( new Element() )
//                                ->setContent('2020/21') //ToDO füllen ?
                                ->stylePaddingLeft()
                                ->styleTextSize($InputText)
                                ->styleBorderRight($OutLines)
                                ->styleHeight('19.5px')
                            )
                            , '30%')
                    )
                )
                ->addSlice(( new Slice() )
                    ->addElement(( new Element() )
                        ->setContent('Besuchte Schulen (von/bis)')//ToDO auslesen aus der Historie (später)
                        ->stylePaddingTop('7px')
                        ->styleBorderTop('0.5px')
                        ->styleBorderRight($OutLines)
                        ->styleBorderLeft($OutLines)
                        ->styleHeight('19px')
                    )
                    ->addElement(( new Element() )
                        ->styleBorderTop('0.5px')
                        ->styleBorderRight($OutLines)
                        ->styleBorderLeft($OutLines)
                        ->styleHeight('26px')
                    )
                    ->addElement(( new Element() )
                        ->styleBorderTop('0.5px')
                        ->styleBorderRight($OutLines)
                        ->styleBorderLeft($OutLines)
                        ->styleHeight('26px')
                    )
                    ->addElement(( new Element() )
                        ->styleBorderTop('0.5px')
                        ->styleBorderRight($OutLines)
                        ->styleBorderLeft($OutLines)
                        ->styleHeight('26px')
                    )
                    ->addElement(( new Element() )
                        ->styleBorderTop('0.5px')
                        ->styleBorderRight($OutLines)
                        ->styleBorderLeft($OutLines)
                        ->styleHeight('26px')
                    )
                    ->addElement(( new Element() )
                        ->styleBorderTop('0.5px')
                        ->styleBorderRight($OutLines)
                        ->styleBorderLeft($OutLines)
                        ->styleBorderBottom($OutLines)
                        ->styleHeight('26px')
                    )
                )
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addElementColumn(( new Element() )
                            ->setContent('¹ Zutreffendes ist zu unterstreichen')
                            ->stylePaddingTop()
                            ->styleTextSize('6px')
                            , '20%')
                        ->addElementColumn(( new Element() )
                            ->setContent('* mit Einwilligung der Eltern')
                            ->stylePaddingTop()
                            ->styleTextSize('6px')
                            , '20%')
                        ->addElementColumn(( new Element() )
                            , '60%')
                    )
                )
                ->addSlice(( new Slice() )
                    ->addElement(( new Element() )
                        ->setContent('&nbsp;')
                        ->stylePaddingTop($SpaceBetween)
                    )
                )
                ->addSlice(( new Slice() )
                    ->addElement(( new Element() )
                        ->setContent('
                        {% if(Content.Student.School.Type is not empty) %}
                            {{ Content.Student.School.Type }}
                        {% else %}
                            &nbsp;
                        {% endif %}
                        ')
                        ->stylePaddingBottom('5px')
                        ->styleTextSize('18px')
                        ->styleTextBold()
                    )
                )
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            ->styleBorderLeft($OutLines)
                            , '5%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            ->styleBorderLeft('0.5px')
                            , '5%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            ->styleBorderLeft('0.5px')
                            , '5%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            ->styleBorderLeft($OutLines)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            ->styleBorderLeft('0.5px')
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            ->styleBorderLeft('0.5px')
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            ->styleBorderLeft('0.5px')
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('Leistungen in den einzelnen Fächern')
                            ->styleAlignCenter()
                            ->styleTextSize('12px')
                            ->styleHeight('16.5px')
                            ->styleBorderTop($OutLines)
                            ->styleBorderLeft($OutLines)
                            ->styleBorderRight($OutLines)
                            ->styleBorderBottom('0.5px')
                            , '49%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            ->styleBorderLeft('0.5px')
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            ->styleBorderLeft('0.5px')
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderTop($OutLines)
                            ->styleBorderRight($OutLines)
                            ->styleBorderLeft('0.5px')
                            , '4%')
                    )
                )
                // HeaderName
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-top: 6px!important;padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Klasse
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft($OutLines)
                            ->styleHeight($HeightForHeader)
                            , '5%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-top: 6px!important;padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Schuljahr
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '5%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-top: 6px!important;padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Schulhalbjahr
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '5%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Betragen
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft($OutLines)
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Fleiß
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Mitarbeit
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Ordnung
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        // Fächer
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft($OutLines)
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Deutsch
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Sachunterricht
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Kunst
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Musik
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Englisch
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Mathematik
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Werken
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Ev./Kath. Religion/Ethik¹
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Sport
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '3%')
                        ->addElementColumn(( new Element() )
                            ->setContent('&nbsp;')
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleBorderRight($OutLines)
                            ->styleHeight($HeightForHeader)
                            , '4%')
                        // letzter Abschnitt
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-top: 3px!important;padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Datum des Zeugnisses
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-top: 3px!important;padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Versetzungsvermerke
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-top: 3px!important;padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Versäumnisse
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '4%')
                        ->addElementColumn(( new Element() )
                            ->setContent('<div 
                        style="padding-top: 3px!important;padding-left: -90px!important;transform: rotate(270deg)!important;">
                                            Signum des Lehrers
                                          </div>')
                            ->styleTextSize($SmallTextSize)
                            ->styleBorderBottom('0.5px')
                            ->styleBorderRight($OutLines)
                            ->styleBorderLeft('0.5px')
                            ->styleHeight($HeightForHeader)
                            , '4%')
                    )
                )
//                ->addSlice(( new Slice() )
//                    ->addSection(( new Section() )
//                        ->addElementColumn(( new Element() )
//                            ->setContent('05a')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft($OutLines)
//                            , '5%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('2016')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '5%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('1.HJ')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '5%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('4')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft($OutLines)
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('2')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('1')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('5')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        // Noten
//                        ->addElementColumn(( new Element() )
//                            ->setContent('&nbsp;')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft($OutLines)
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('&nbsp;')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('3')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('1')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('5')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('4')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('1')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('2')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('2')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('--')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('1')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('&nbsp;')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('&nbsp;')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('&nbsp;')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('&nbsp;')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '3%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('&nbsp;')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderRight($OutLines)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '4%')
//                        // letzer Abschnitt
//                        ->addElementColumn(( new Element() )
//                            ->setContent('17')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            , '4%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('Nein')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '4%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('11')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '4%')
//                        ->addElementColumn(( new Element() )
//                            ->setContent('X')
//                            ->styleAlignCenter()
//                            ->stylePaddingTop($InputFieldTop)
//                            ->styleTextSize($InputFieldTextSize)
//                            ->styleHeight($InputFieldHeight)
//                            ->styleBorderRight($OutLines)
//                            ->styleBorderBottom('0.5px')
//                            ->styleBorderLeft('0.5px')
//                            , '4%')
//                    )
//                )
                ->addSlice(( new Slice() )
                    ->addSectionList($this->GradeFieldSectionList(12, $OutLines, $InputFieldTop, $InputFieldTextSize, $InputFieldHeight))
                )
                ->addSlice(( new Slice() )
                    ->addElement(( new Element() )
                        ->styleBorderTop('0.7px')
                    )
                )
                ->addSlice(( new Slice() )
                    ->addSection(( new Section() )
                        ->addElementColumn(( new Element() )
                            ->setContent('¹ Zutreffendes ist zu unterstreichen')
                            ->stylePaddingTop()
                            ->styleTextSize('6px')
                            , '20%')
                        ->addElementColumn(( new Element() )
                            , '80%')
                    )
                )
            )
        );
    }

    /**
     * @param int    $count
     * @param string $OutLines
     * @param string $InputFieldTop
     * @param string $InputFieldTextSize
     * @param string $InputFieldHeight
     *
     * @return array
     */
    private function GradeFieldSectionList(
        $count = 1,
        $OutLines = '2px',
        $InputFieldTop = '4px',
        $InputFieldTextSize = '13px',
        $InputFieldHeight = '17px'
    ) {

        $SectionList = array();
        for ($i = 0; $i < $count; $i++) {
            $SectionList[] =
                ( new Section() )
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft($OutLines)
                        , '5%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '5%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '5%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft($OutLines)
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    // Noten
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft($OutLines)
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '3%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderRight($OutLines)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '4%')
                    // letzer Abschnitt
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        , '4%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '4%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '4%')
                    ->addElementColumn(( new Element() )
                        ->setContent('&nbsp;')
                        ->styleAlignCenter()
                        ->stylePaddingTop($InputFieldTop)
                        ->styleTextSize($InputFieldTextSize)
                        ->styleHeight($InputFieldHeight)
                        ->styleBorderRight($OutLines)
                        ->styleBorderBottom('0.5px')
                        ->styleBorderLeft('0.5px')
                        , '4%');
        }

        return $SectionList;
    }
}